compilers:
  gcc:
    - 6.2.0
    - 6.3.0
    - 6.4.0
    - 7.1.0
    - 7.2.0
    - 7.3.0
    - 7.4.0
    - 8.1.0
    - 8.2.0
    - 8.3.0
  clang:
    - 6.0.0
    - 8.0.0
base_url: https://s3.amazonaws.com/compiler-explorer/opt
base_path: /opt/toolchain
