#!/usr/bin/env ruby

#----- System Requires -----#

require 'optimist'

#----- Setup Logic -----#

# Get CLI options.
@opts = Optimist.options do
  opt :daemonize, "Don't attach to the container", default: false, short: '-d'
  opt :name, 'What to name the container', type: :string, short: '-n'
  opt :rm, 'Whether the image should be removed upon exit', default: false
end

def image_name
  'cfretz244/libdart_ci:msvc_dev'
end

def container_name
  proj_name = @opts[:name] || ENV['project_name'] || 'dart_dev'
  "#{proj_name}_msvc_2019"
end

BASE_DIR = File.expand_path(File.dirname(__FILE__))

#----- Application Logic -----#

# Start the container.
flags = "-it --privileged -v=#{File.join(BASE_DIR, 'deps', 'libdart', 'include')}:/usr/local/include"
flags += " --name #{container_name}"
if @opts[:rm]
  system("docker run #{flags} --rm #{image_name} bash")
else
  `docker create #{flags} #{image_name} bash`
  `docker start #{container_name}`
  system("docker attach #{container_name}") unless @opts[:daemonize]
end
