#!/usr/bin/env ruby

#----- System Requires -----#

require 'optimist'

#----- Setup Logic -----#

# Get CLI options.
@opts = Optimist.options do
  opt :daemonize, "Don't attach to the container", default: false, short: '-d'
  opt :name, 'What to name the container', type: :string, short: '-n'
  opt :rm, 'Whether the image should be removed upon exit', default: false
end

def image_name
  'cfretz244/libdart_ci:msvc_dev'
end

def container_name
  proj_name = @opts[:name] || ENV['project_name'] || 'dart_dev'
  "#{proj_name}_msvc_2019"
end

#----- Application Logic -----#

# Start the container.
if @opts[:rm]
  system("docker run -it --rm --privileged --name #{container_name} #{image_name} bash")
else
  `docker create -it --privileged --name #{container_name} #{image_name} bash`
  `docker start #{container_name}`
  system("docker attach #{container_name}") unless @opts[:daemonize]
end
